#!/bin/bash

# Fake fw_printenv file
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z "$1" ]
then
    cat $DIR/fw_env_bootcount
    cat $DIR/fw_env_upgrade_available
else
    FILENAME="fw_env_$1"
    # echo
    # echo FILENAME=$FILENAME
    # echo DIR=$DIR
    cat $DIR/$FILENAME
fi
