#!/bin/bash


echo
echo Running fake reboot script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo DIR variable = $DIR
date
echo Attempting to write to $DIR/last_reboot.txt

date > $DIR/last_reboot.txt
echo fake reboot done.
echo
